<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;

class BranchReport extends Model
{
    protected $fillable = [
        'branch_id',
        'submitted_by',
        'week_ending',
        'total_mcs_reporting',
        'total_members_met',
        'total_new_members',
        'total_salvations',
        'total_anagkazo',
        'total_offerings',
        'branch_activities',
        'training_conducted',
        'challenges',
        'prayer_requests',
        'goals_next_week',
        'comments',
        'status',
        'reviewed_by',
        'reviewed_at',
        'review_comments',
        'is_auto_generated',
        'sent_to_super_admin',
        'sent_at',
    ];

    protected $casts = [
        'week_ending' => 'date',
        'reviewed_at' => 'datetime',
        'sent_at' => 'datetime',
        'total_offerings' => 'decimal:2',
        'is_auto_generated' => 'boolean',
        'sent_to_super_admin' => 'boolean',
    ];

    /**
     * Get the branch this report belongs to
     */
    public function branch(): BelongsTo
    {
        return $this->belongsTo(Branch::class);
    }

    /**
     * Get the user who submitted this report
     */
    public function submittedBy(): BelongsTo
    {
        return $this->belongsTo(User::class, 'submitted_by');
    }

    /**
     * Get the user who reviewed this report
     */
    public function reviewedBy(): BelongsTo
    {
        return $this->belongsTo(User::class, 'reviewed_by');
    }

    /**
     * Mark as sent to super admin
     */
    public function markAsSent(): void
    {
        $this->update([
            'sent_to_super_admin' => true,
            'sent_at' => now(),
        ]);
    }

    /**
     * Scope for auto-generated reports
     */
    public function scopeAutoGenerated($query)
    {
        return $query->where('is_auto_generated', true);
    }

    /**
     * Scope for reports not yet sent to super admin
     */
    public function scopeNotSent($query)
    {
        return $query->where('sent_to_super_admin', false);
    }
}
